support to set `dbus/vendored`
Mange/mpris-rs pull request #74
Opened 2024-01-10 14:45 UTC by poly000

2024-01-11 07:58 UTC, Mange commented
Please explain what this is supposed to accomplish. :-)

2024-01-11 08:25 UTC, mokurin000 commented
> Please explain what this is supposed to accomplish. :-)

without this patch, users of `mpris-rs` will need to add `dbus` to their dependencies to set "dbus/vendored"

or they could simply intro "mpris/vendored" to make dbus build vendored

2024-01-12 12:30 UTC, Mange commented
`dbus-rs` defines this feature as such:

> The `vendored` feature links libdbus statically into the final executable.

Seems useful, yes.

2024-01-12 12:31 UTC, Mange requested changes

2024-01-12 12:31 UTC, Mange commented on Cargo.toml
> +vendored = ["dbus/vendored"]
Let's rename the feature to `dbus-vendored`.

2024-01-15 07:21 UTC, merged

2024-01-15 07:21 UTC, Mange commented
Thank you!