chore: migrate to strum::EnumIs
Mange/mpris-rs pull request #77
Opened 2024-02-22 15:53 UTC by poly000

derive_is_variant has not been update for several years, while `strum` is under active developement

close #76

2024-02-28 20:12 UTC, Mange requested changes
This looks cool and all, but `is_f64` changing to `is_f_64` is a breaking change.

Strum does not offer custom naming in their derive macro, so I think the play here is to manually add all the `is_xn` methods and delegate to the `is_x_n` version.

Perhaps even mark the old names as deprecated or something.

---

I think I should open a feature request on strum to ask for

```rust
#[derive(EnumIs)]
pub enum Foo {
  Baz, // is_baz

  #[strum(name = "pub")]
  Bar, // is_pub
}
```

You could also do that, if you wish. I don't have time for it right now, sadly.

2024-02-28 21:28 UTC, Mange commented
Eh, I added a PR to `strum` to get custom names. I found the time.

https://github.com/Peternator7/strum/pull/336

Let's wait for this before progressing on this PR.

2024-04-01 06:42 UTC, poly000 commented
@Mange how if we provide `is_f64` that calling `self.is_f_64()`
until users defined `is_f_64` in their traits for `Value`, (and in this case they should check out [fully-qualified-syntax](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name))

2024-04-01 18:23 UTC, Mange commented
> @Mange how if we provide `is_f64` that calling `self.is_f_64()` […]

I am fine with this, but I really want to make sure we can mark the generated `is_f_64` as being deprecated.

> […] until users defined `is_f_64` in their traits for `Value`, this won't be a breaking change […]

No, if we add new methods (`is_f_64`), then removing those becomes the breaking change instead.  I'm not worried about people implementing `Value` themselves, only that they try to use `Value` in their own code and use `is_f_64`/`is_f64` in a way that breaks during a version upgrade.

I don't want duplicated methods like this. Note that this is for all the number types, not just `f64`.
 
> `strum` ignored the rename support PR for weeks

Yeah, it's really unfortunate… I suspect that maintainer has a lot going on right now.

---

Maybe the best way forward is to remove `derive_is_variant` (the problem in question) and manually implementing the `is_X` methods without `strum` or any other macro. It's not too hard, honestly. I bet ChatGPT or Copilot could whip them out pretty quickly after one or two of them are already implemented.

I could do it if you don't feel motivated to do it yourself. :-)

2024-04-02 04:34 UTC, closed without merging