Fix feature = "cargo-clippy" deprecation
Mange/mpris-rs pull request #78
Opened 2024-02-28 14:53 UTC by rex4539

https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html

2024-02-28 19:55 UTC, Mange requested changes
Thank you for bringing this to my attention. :heart: 

Would you mind checking out this suggestion before I merge?

2024-02-28 19:55 UTC, Mange commented on src/metadata.rs
> +#[cfg_attr(clippy, allow(clippy::implicit_hasher))]
Seems like it would be enough with just `#[allow(clippy::implicit_hasher)]`, according to the linked article. :-)

2024-02-28 23:25 UTC, rex4539 commented
Let's try again :)

2024-02-29 07:55 UTC, Mange approved these changes
Thank you!

2024-02-29 07:55 UTC, merged