Improve player name detection
Mange/mpris-rs pull request #84
Opened 2024-06-07 22:37 UTC by Kanjirito

Fixes #81 
Instead of just assuming the first part of the bus name is the player name it now instead checks if the last part is a instance part named like the example in the MPRIS spec (`instanceID`). If yes then the second to last part gets used.

This fully depends on whether players implement the instance part this way so it will require some further testing with more players but I don't believe there's another way to do this.

And I am aware that there's a rewrite branch but I haven't used it yet so it was simpler for me to do it here for now.

2024-06-08 09:31 UTC, ravener commented
I repeat here that 'Flatpak name parts' is a misleading term, they are called [Application ID](https://developer.gnome.org/documentation/tutorials/application-id)s, and even non-flatpak apps are encouraged to use them.

I'm also not sure what to feel about completely omitting those parts, on one hand, this gets pretty close to what `player.identity()` is for since that must return the player name and nothing related to the bus name.

2024-06-08 14:02 UTC, Kanjirito commented
Oh I was not aware that GNOME uses that ID system overall. I'll keep that in mind if this goes anywhere.

I do agree that it should return the whole bus string just without the MPRIS prefix and the instance part if it gets detected. I kinda forgot that the point was to get the all of the name parts of the bus and not just the name itself.

And the check is mostly there for the `len() == 1` case since a player that has a bus name that only has one part which starts with "instance" would cause a crash. `len() == 3` just catches the edge case of something like `org.github.instance` since as I've mentioned before 3 parts mean that it's a GNOME ID without an instance part. It's technically not needed since I doubt there will be a player called that but with the check the edge case will only show up if a player has a longer ID and is called something that starts "instance" at which point there's just no way of knowing for sure.

2024-06-09 13:44 UTC, Mange requested changes
Although this doesn't solve all the issues in the original bug report, this does appear to fix at least _some_ of those issues and I think its inclusion could be a net-positive.

No need to let the perfect be the enemy of good here.

I do wish to add some unit tests for this to make problems easier to visualize with realistic examples. I don't think it would be easy to set up fake `Player` instances, so if you cannot get that to work nicely, consider moving the implementation out to a free method in this module and then embedding some tests to test it without needing to export it.

```rust
pub fn bus_name_player_name_part(&self) -> &str {
  extract_player_name_part(&self.bus_name)
}

///

fn extract_player_name_part(bus_name: &str) -> &str {
  // ...
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn it_extracts_common_player_names_from_bus() {
    assert_eq!("org.mpris.MediaPlayer2.Spotify.instance2", "Spotify")
    // ...
  }
}
```

2024-06-13 13:59 UTC, Kanjirito commented
This should be all unless you want me to reword something.

2024-06-15 10:49 UTC, Mange approved these changes
Perfect! :heart_eyes:

2024-06-15 10:49 UTC, merged

2026-04-18 10:15 UTC, Mange commented
Version 2.1.0 was just released with this change.